# Generated by Django 5.0.3 on 2024-06-03 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=255)),
                ('envoyeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envoyeur', to='Accounts.utilisateur')),
                ('receveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receveur', to='Accounts.utilisateur')),
            ],
        ),
    ]
